services:
  - type: web
    name: interview-plateform
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_GENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
